WebApp/TaalDc.Portal/Controllers/BuyersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Engineering;
using System.Net.Mail;
using TaalDc.Portal.DTO.Enums;
using TaalDc.Portal.DTO.Sales.Buyer;
using TaalDc.Portal.DTO.Sales.Contracts;
using TaalDc.Portal.Services;
using WebApplication2.Controllers;

namespace TaalDc.Portal.Controllers
{
    [Authorize("LimitedCustodian")]
    public class BuyersController : Controller
    {
        private readonly ILogger<BuyersController> _logger;
        private readonly ISalesService _salesService;

        public BuyersController(ILogger<BuyersController> logger
            ,ISalesService salesService)
        {
            _logger = logger;
            _salesService = salesService;
        }

        public async Task<IActionResult> Index(int pageNumber=1, int pageSize=10, string name = "", string email = "")
        {
            var buyers = await _salesService.GetBuyers(pageNumber, pageSize, name, email);

            return View(buyers);
        }

        public IActionResult QuickCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BuyerCreate_ClientDto model)
        {
            //Check if model is valid
            //If valid, send request to API
            //If not, return back the with error
            if(ModelState.IsValid)
            {
                var buyer = new AddBuyerRequest(
                    model.Salutation
                   , model.FirstName
                   , model.MiddleName
                   , model.LastName
                   , model.EmailAddress
                   , ""
                   , model.MobileNo
                   , DateTime.MinValue
                   , 1
                   , new AddressDto(model.HomeAddress, model.HomeCity, model.HomeState, model.HomeCountry, model.HomeZipCode)
                   , model.IsCorporate
                   ,new CompanyDto(model.CompanyName, model.CompanyAddress, model.CompanyIndustry, "", "", "", "", "", "", "", "")
                   );

                try
                {
                    var result = await _salesService.AddBuyer(buyer);

                    if (result.IsSuccess) { 
                        return Ok(new 
                        {
                            result.Id,
                            IsFormError = false,
                            Message = ""
                        });
                    }
                    else
                    {
                        return BadRequest(new
                        {
                            IsFormError = false,
                            Message = result.ErrorMessage
                        });
                    }

                }
                catch(Exception err)
                {
                    return BadRequest(new
                    {
                        IsFormError = false,
                        err.Message
                    });
                }
            }

            return BadRequest(new
            {
                IsFormError = true,
                Message = "Please check your entry.",
                ModelState = Json(ModelState)
            });
        }


        public async Task<IActionResult> Details(int id)
        {
            var buyerQueryResult = await _salesService.GetBuyer(id);
            
            var buyer = new Buyer_ClientDto(
                buyerQueryResult.Salutation
                ,buyerQueryResult.FirstName
                ,buyerQueryResult.MiddleName
                ,buyerQueryResult.LastName
                ,buyerQueryResult.Dob
                ,buyerQueryResult.CivilStatusId
                ,buyerQueryResult.CivilStatus
                );

            buyer.BrokerName = buyerQueryResult.BrokerName;
            buyer.BrokerEmail = buyerQueryResult.BrokerEmail;
            buyer.BrokerCompany = buyerQueryResult.BrokerCompany;
            buyer.BrokerPRCLicense = buyerQueryResult.BrokerPRCLicense;

            buyer.Id = id;

            buyer.SetContactDetails(buyerQueryResult.EmailAddress, buyerQueryResult.MobileNo, buyerQueryResult.PhoneNo);

            buyer.SetIDInformation(buyerQueryResult.Occupation, buyerQueryResult.Tin, buyerQueryResult.GovIssuedId, buyerQueryResult.GovIssuedIdValidUntil);

            buyer.HomeAddress = new ClientAddress(
                    buyerQueryResult.HomeAddress_Street, 
                    buyerQueryResult.HomeAddress_City, 
                    buyerQueryResult.HomeAddress_State, 
                    buyerQueryResult.HomeAddress_Country, 
                    buyerQueryResult.HomeAddress_ZipCode);

            buyer.BillingAddress = new ClientAddress(
                    buyerQueryResult.BillingAddress_Street,
                    buyerQueryResult.BillingAddress_City,
                    buyerQueryResult.BillingAddress_State,
                    buyerQueryResult.BillingAddress_Country,
                    buyerQueryResult.BillingAddress_ZipCode);

            buyer.BusinessAddress = new ClientAddress(
                    buyerQueryResult.BusinessAddress_Street,
                    buyerQueryResult.BusinessAddress_City,
                    buyerQueryResult.BusinessAddress_State,
                    buyerQueryResult.BusinessAddress_Country,
                    buyerQueryResult.BusinessAddress_ZipCode);

            buyer.IsCorporate = buyerQueryResult.IsCorporate;

            buyer.Company = new Company(buyerQueryResult.Company_Name, 
                buyerQueryResult.Company_Address,
                buyerQueryResult.Company_Industry,
                buyerQueryResult.Company_PhoneNo,
                buyerQueryResult.Company_MobileNo,
                buyerQueryResult.Company_FaxNo,
                buyerQueryResult.Company_EmailAddress,
                buyerQueryResult.Company_TIN,
                buyerQueryResult.Company_SECRegNo,
                buyerQueryResult.Company_President,
                buyerQueryResult.Company_CorpSec);

            buyer.SpouseId = buyerQueryResult.PartnerId;

            if (buyerQueryResult.PartnerId.HasValue && buyerQueryResult.PartnerId.Value > 0) {
                var spouseResult = await _salesService.GetBuyer(buyerQueryResult.PartnerId.Value);
                var spouse = new Buyer_ClientDto(spouseResult.Salutation, spouseResult.FirstName, spouseResult.MiddleName, spouseResult.LastName, spouseResult.Dob, 2, "Married");

                spouse.SetContactDetails(spouseResult.EmailAddress, spouseResult.MobileNo, spouseResult.PhoneNo);

                spouse.SetIDInformation(spouseResult.Occupation, spouseResult.Tin, spouseResult.GovIssuedId, spouseResult.GovIssuedIdValidUntil);

                spouse.Id = buyerQueryResult.PartnerId.Value;

                buyer.Spouse = spouse;
            }

            return View(buyer);
        }


        public async Task<IActionResult> Contracts(int id) {

            var buyerContracts = await _salesService.GetBuyerContracts(id);

            ViewData["BuyerId"] = id;

            return View(buyerContracts);
        }


        [HttpPost]
        public async Task<IActionResult> EditGeneralInfo(UpdateBuyerInfoRquest model)
        {
            await _salesService.UpdateBuyerInfo(model);

            return Ok();
        }


        [HttpPost]
        public async Task<IActionResult> EditContactInfo(UpdateBuyerContactRequest model)
        {
            await _salesService.UpdateBuyerContact(model);

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> EditAddress(PatchBuyerAddressRequest model)
        {
            await _salesService.PatchBuyerAddress(model);

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> EditIDInformation(UpdateBuyerMiscRequest model)
        {
            await _salesService.UpdateBuyerMisc(model);

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> EditCompanyInformation(UpdateBuyerCompanyRequest model)
        {
            model.MobileNo = !string.IsNullOrEmpty(model.MobileNo) ? model.MobileNo : "";
            model.FaxNo = !string.IsNullOrEmpty(model.FaxNo) ? model.FaxNo : "";
           
            await _salesService.UpdateBuyerCompany(model);

            return Ok();
        }


        [HttpPost]
        public async Task<IActionResult> EditSpouse(UpsertBuyerSpouseRequest model)
        {
            return Ok(await _salesService.UpsertSpouse(model));
        }
    }
}

WebApp/TaalDc.Portal/Controllers/InquiriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaalDc.Portal.DTO.Marketing;
using TaalDc.Portal.Services;

namespace TaalDc.Portal.Controllers;


public class InquiriesController : BaseController<InquiriesController>
{
    private readonly IMarketingService _marketingService;

    public InquiriesController(IMarketingService marketingService, ILogger<InquiriesController> loggerInstance) :
        base(loggerInstance)
    {
        _marketingService = marketingService;
    }

    public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10, int status = 1)
    {
        var result = await _marketingService.GetInquiries(pageSize, pageNumber, status);
        return View(result);
    }

    public async Task<IActionResult> Closed(int pageNumber = 1, int pageSize = 10, int status = 3)
    {
        var result = await _marketingService.GetInquiries(pageSize, pageNumber, status);
        return View(result);
    }


    public async Task<IActionResult> Details(int id)
    {
        var inquiry = await _marketingService.GetInquiryById(id);

        return View(inquiry);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateInquiryStatus(UpdateInquiryStatusDto dto)
    {
        await _marketingService.UpdateInquiryStatus(dto);

        return Ok();
    }
}

WebApp/TaalDc.Portal/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaalDc.Portal.Controllers;
using TaalDc.Portal.Services;
using TaalDc.Portal.ViewModels.Users;

namespace WebApplication2.Controllers;

[Authorize(Policy = "AdminOnly")]
public class UsersController : BaseController<UsersController>
{
    private readonly IAccountService _accountService;

    public UsersController(
        ILogger<UsersController> loggerInstance,
        IAccountService accountService) : base(loggerInstance)
    {
        _accountService = accountService;
    }

    public async Task<IActionResult> Index()
    {
        var vm = await _accountService.GetListOfUsers();
        return View(vm);
    }

    public async Task<IActionResult> CreateUser()
    {
        //get dropdown of roles
        ViewData["Roles"] = await _accountService.GetRolesAsync();

        return View();
    }


    [HttpPost("post")]
    public async Task<IActionResult> Post(UserCreateDto model)
    {
        var result = await _accountService.CreateUser(model);

        if (string.IsNullOrEmpty(result)) return RedirectToAction(nameof(Index));

        //get dropdown of roles
        ViewData["Roles"] = await _accountService.GetRolesAsync();
        ViewData["Errors"] = result;
        return RedirectToAction(nameof(CreateUser));
    }

    public async Task<IActionResult> UpdateUser(string id)
    {
        var user = await _accountService.GetUserById(id);
        //get dropdown of roles
        ViewData["Roles"] = await _accountService.GetRolesAsync();

        UserUpdateDto model = new()
        {
            Id = id,
            Emailaddress = user.Email.Normalize(),
            FirstName = user.FirstName,
            LastName = user.LastName,
            MiddleName = user.MiddleName,
            NameSuffix = user.NameSuffix,
            Company = user.Company,
            PRCLicense = user.PRCLicense,
            Role = user.Roles.FirstOrDefault() ?? string.Empty,
            IsActive = user.Roles.Any(),
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Put(string id, UserUpdateDto model)
    {
        var result = await _accountService.UpdateUser(model.Id, model, false);

        if (string.IsNullOrEmpty(result)) return RedirectToAction(nameof(Index));

        ViewData["Roles"] = await _accountService.GetRolesAsync();

        return RedirectToAction(nameof(UpdateUser), model);
    }


}

WebApp/TaalDc.Portal/Views/Shared/_AddressForm.cshtml
@model TaalDc.Portal.DTO.Sales.Buyer_ClientDto


@{

}

<!--Address Edit Modal-->
<div class="modal fade" id="addressModal" tabindex="-1" aria-labelledby="addressModal" aria-hidden="true">
    <div class="modal-dialog  modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Address</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="formLoader">
                    <ul class="formLoading">
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <form class="row needs-validation" method="post" id="addressForm" asp-action="EditAddress" asp-controller="Buyers" asp-route-id="@Model.Id">
                    <input name="BuyerId" value="@Model.Id" hidden />
                    <input name="Type" hidden />

                    <div class="col-lg-12">
                        <label class="form-label">
                            <strong>Address</strong>
                        </label>
                    </div>

                    <div class="mb-3 col-lg-8">
                        <input name="Street" class="form-control" placeholder="Street/Brgy/Ave." required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-4">
                        <input name="City" class="form-control" placeholder="City" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-4">
                        <input name="State" class="form-control" placeholder="State" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-4">
                        <input name="Country" class="form-control" placeholder="Country" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-4">
                        <input name="ZipCode" class="form-control" placeholder="Zip Code" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <input class="btn btn-primary" type="submit" value="Save" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApp/TaalDc.Portal/Views/Shared/_CompanyForm.cshtml
@model TaalDc.Portal.DTO.Sales.Buyer_ClientDto


<!--Company Edit Modal-->
<div class="modal fade" id="companyModal" tabindex="-1" aria-labelledby="companyModal" aria-hidden="true">
    <div class="modal-dialog  modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Company Information</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="formLoader">
                    <ul class="formLoading">
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <form class="row needs-validation" method="post" id="companyForm" asp-action="EditCompanyInformation" asp-controller="Buyers" asp-route-id="@Model.Id">
                    <input name="BuyerId" value="@Model.Id" hidden />

                    <div class="mb-3 col-lg-12">
                        <label for="Name" class="form-label">
                            <strong>Name</strong>
                        </label>
                        <input name="Name" class="form-control" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-12">
                        <label for="Address" class="form-label">
                            <strong>Address</strong>
                        </label>
                        <input name="Address" class="form-control" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-12">
                        <label for="Industry" class="form-label">
                            <strong>Industry</strong>
                        </label>
                        <input name="Industry" class="form-control" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                     <div class="mb-3 col-lg-6">
                        <label for="PhoneNo" class="form-label">
                            <strong>Phone No</strong>
                        </label>
                        <input name="PhoneNo" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                     <div class="mb-3 col-lg-6">
                        <label for="MobileNo" class="form-label">
                            <strong>Mobile No</strong>
                        </label>
                        <input name="MobileNo" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                     </div>

                     <div class="mb-3 col-lg-6">
                        <label for="FaxNo" class="form-label">
                            <strong>Fax No</strong>
                        </label>
                        <input name="FaxNo" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-12">
                        <label for="EmailAddress" class="form-label">
                            <strong>Email Address</strong>
                        </label>
                        <input name="EmailAddress" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-6">
                        <label for="TIN" class="form-label">
                            <strong>TIN</strong>
                        </label>
                        <input name="TIN" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                     <div class="mb-3 col-lg-6">
                        <label for="SECRegNo" class="form-label">
                            <strong>SEC Reg No</strong>
                        </label>
                        <input name="SECRegNo" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                     <div class="mb-3 col-lg-6">
                        <label for="President" class="form-label">
                            <strong>President</strong>
                        </label>
                        <input name="President" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                     <div class="mb-3 col-lg-6">
                        <label for="CorpSec" class="form-label">
                            <strong>Corp Sec</strong>
                        </label>
                        <input name="CorpSec" class="form-control" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>


                     <div class="mb-3 col-lg-12">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" asp-for="IsCorporate">
                            <label class="form-check-label" asp-for="IsCorporate">Corporate Account?</label>
                        </div>
                    </div>
                 

                    <div class="col-lg-12">
                        <input class="btn btn-primary" type="submit" value="Save" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApp/TaalDc.Portal/Views/Shared/_ContactInfoForm.cshtml
@model TaalDc.Portal.DTO.Sales.Buyer_ClientDto

<!--Contact Info Edit Modal-->
<div class="modal fade" id="contactInfoModal" tabindex="-1" aria-labelledby="contactInfoModal" aria-hidden="true">
    <div class="modal-dialog  modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Contact Information</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="formLoader">
                    <ul class="formLoading">
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <form class="row needs-validation" method="post" id="contactInfo" asp-action="EditContactInfo" asp-controller="Buyers" asp-route-id="@Model.Id">
                    <input name="BuyerId" value="@Model.Id" hidden />
                    <div class="mb-3 col-lg-12">
                        <label for="EmailAddress" class="form-label">
                            <strong>Email Address</strong>
                        </label>
                        <input name="EmailAddress" class="form-control" required type="email" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-12">
                        <label for="PhoneNo" class="form-label">
                            <strong>Phone No.</strong>
                        </label>
                        <input name="PhoneNo" class="form-control" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-12">
                        <label for="MobileNo" class="form-label">
                            <strong>Mobile No.</strong>
                        </label>
                        <input name="MobileNo" class="form-control" required />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <input class="btn btn-primary" type="submit" value="Save" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApp/TaalDc.Portal/Views/Shared/_GeneralInfoForm.cshtml
@model TaalDc.Portal.DTO.Sales.Buyer_ClientDto

<!--General Info Edit Modal-->
<div class="modal fade" id="generalInfoModal" tabindex="-1" aria-labelledby="generalInfoModal" aria-hidden="true">
    <div class="modal-dialog  modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">General Information</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="formLoader">
                    <ul class="formLoading">
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <form class="row needs-validation" method="post" id="generalinfo" asp-action="EditGeneralInfo" asp-controller="Buyers" asp-route-id="@Model.Id">
                    <input name="BuyerId" value="@Model.Id" hidden />
                    <div class="col-lg-12">
                        <label class="form-label">
                            <strong>Customer Name</strong>
                        </label>
                    </div>

                    <div class="mb-3 col-lg-2">
                        <select name="Salutation" class="form-control form-select" required>
                            <option value="Mr.">
                                Mr.
                            </option>
                            <option value="Ms.">
                                Ms.
                            </option>
                            <option value="Mrs.">
                                Mrs.
                            </option>
                        </select>
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="col-lg-10 row px-0">
                        <div class="mb-3 col-lg-4">
                            <input name="FirstName" class="form-control" required placeholder="First Name" />
                            <div class="invalid-feedback">
                                This is a required field.
                            </div>
                        </div>

                        <div class="mb-3 col-lg-4">
                            <input name="MiddleName" class="form-control" placeholder="Middle Name" />
                            <div class="invalid-feedback">
                                This is a required field.
                            </div>
                        </div>


                        <div class="mb-3 col-lg-4">
                            <input name="LastName" class="form-control" required placeholder="Last Name" />
                            <div class="invalid-feedback">
                                This is a required field.
                            </div>
                        </div>
                    </div>
                    <div class="mb-3 col-lg-12">
                        <label for="DoB" class="form-label">
                            <strong>Date of Birth</strong>
                        </label>
                        <input name="DoB" class="form-control" required type="date" />
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>

                    <div class="mb-3 col-lg-12">
                        <label for="CivilStatusId" class="form-label">
                            <strong>Civil Status</strong>
                        </label>
                        <select name="CivilStatusId" class="form-control form-select" required>
                            <option value="1">
                                Single
                            </option>
                            <option value="2">
                                Married
                            </option>
                            <option value="3">
                                Widowed
                            </option>
                            <option value="4">
                                Widowed
                            </option>
                            <option value="5">
                                Widowed
                            </option>
                            <option value="6">
                                Others
                            </option>
                        </select>
                        <div class="invalid-feedback">
                            This is a required field.
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <input class="btn btn-primary" type="submit" value="Save" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApp/TaalDc.Portal/Views/Shared/_Sidebar.cshtml
@using SeedWork
@inject IAmCurrentUser CurrentUser;


<li class="nav-item">
    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link align-middle px-0">
        Dashboard
    </a>
</li>
@if (CurrentUser.Roles.Contains("ADMIN") || CurrentUser.Roles.Contains("BROKER") || CurrentUser.Roles.Contains("SALES"))
{
    <li class="nav-item">
        <a asp-area="" asp-controller="Sales" asp-action="Index" class="nav-link align-middle px-0">
            Sales
        </a>
    </li>

    <li class="nav-item">
        <a asp-area="" asp-controller="Buyers" asp-action="Index" class="nav-link align-middle px-0">
            Buyers
        </a>
    </li>
}
@if (CurrentUser.Roles.Contains("ADMIN"))
{
    <li class="nav-item">
        <a asp-area="" asp-controller="Properties" asp-action="Index" class="nav-link align-middle px-0">
            Properties
        </a>
    </li>
    <li class="nav-item">
        <a asp-area="" asp-controller="Inquiries" asp-action="Index" class="nav-link align-middle px-0">
            Inquiries
        </a>
    </li>
    <li class="nav-item">
        <a asp-area="" asp-controller="Users" asp-action="Index" class="nav-link align-middle px-0">
            Settings
        </a>
    </li>
}